# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
library(googleCloudStorageR)
library(googleAuthR)
library(dplyr)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(ranger)
    library(recipes)
    library(workflows)
}

## google cloud storage
gcs_auth(json_file = "/opt/ml/titanic-466214-95c689d94120.json")

### google cloud boar
b <- board_gcs("titanic-model-1602", prefix = NULL)
v <- vetiver_pin_read(b, "titanic_survived_predictor")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
