# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(ranger)
    library(recipes)
    library(workflows)
}
b <- board_folder(path = "/titanic-model-1602")
v <- vetiver_pin_read(b, "titanic_survived_predictor")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
