# Generated by the vetiver package; edit with care


library(pins)

library(plumber)
library(rapidoc)
library(vetiver)
library(googleCloudStorageR)
library(gargle)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(ranger)
    library(recipes)
    library(workflows)
}
if (file.exists("titanic-466214-95c689d94120.json")) {
  message("🔑 Using local JSON key for GCS auth")
  gcs_auth("titanic-466214-95c689d94120.json")
} else {
  message("🔑 Using Application Default Credentials (Cloud Run)")
  token <- gargle::token_fetch(
      scopes = "https://www.googleapis.com/auth/cloud-platform"
    )
    gcs_auth(token = token)
}

b <- board_gcs(bucket =  "titanic-model-1602")
v <- vetiver_pin_read(b, "titanic_survived_predictor")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
